name: Run Python Script

on: [push] # Triggers the workflow on every push to the repository

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    - uses: actions/checkout@v4 # Checks out the repository code
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Specifies the Python version (e.g., '3.9', '3.10')
        SECRET_PASSPHRASE: ${{ SECRET_PASSPHRASE.SECRET_PASSPHRASE }}

    - name: Run Python script
      env: # Or as an environment variable
        SECRET_PASSPHRASE: ${{ SECRET_PASSPHRASE.SECRET_PASSPHRASE }}
      run: python my_script.py "$SECRET_PASSPHRASE" # Executes your Python script
